package com.store.reconciliation.Models;

public enum DiscrepancyType {
    UNPAID_COMPLETED_ORDER,
    UNRECORDED_ORPHAN_PAYMENT,
    DUPLICATE_PAYMENT_CHARGE,
    DUPLICATE_ORDER_RECORD,
    PAYMENT_FAILED_ON_COMPLETED,
    PAYMENT_PENDING_ON_COMPLETED,
    CANCELLED_ORDER_PAYMENT_SETTLED,
    PARTIAL_REFUND_MISMATCH,
    CURRENCY_MISMATCH,
    AMOUNT_MISMATCH,
    ROUNDING_VARIANCE
}
